#!/usr/bin/env bash

# Titulo: Post-install para Sway en Archlinux
# Autor: Hector Iván Vega Zamudio
# Correo: mxhectorvega@gmail.com
# Link: https://github.com/mxhectorvega
# Versión:v9.0
# Fecha de actualización 12/06/2022
# Nota: El sistema de preferencia tuvo que haber sido instalado con la herramienta archinstall del liveUSB,
# Seleccionando el perfil Sway con todos los controladores de código abierto.

# Pacman configuraciones
clear 
printf '\n \nConfigurando gestor de paquetes Pacman...\n'
sleep 1
sudo sed -i "s/#Color/Color/g" /etc/pacman.conf 
sudo sed -i "s/#ParallelDownloads/ParallelDownloads/g" /etc/pacman.conf
sudo sed -i "38i ILoveCandy" /etc/pacman.conf

# Paquetes adicionales
clear
printf '\n \nInstalando paquetes adicionales...\n'
sleep 1

# Actualizacion del SO
sudo pacman -Syu --noconfirm
sudo pacman -S git --noconfirm

# Dotfiles Fedora en Arch
clear
printf '\n \nEscribe la contraseña para reemplazar archivo .bashrc...\n'
sudo rm -rf "$HOME"/.bashrc

clear
printf '\n \nClonando repositorios mxhectorvega...\n'
sleep 1

git clone https://github.com/mxhectorvega/sway-arch
git clone https://github.com/mxhectorvega/tipografias
git clone https://github.com/mxhectorvega/temas

cp -rf $HOME/sway-arch/.gtkrc-2.0 "$HOME"
cp -rf $HOME/sway-arch/.bashrc "$HOME"
cp -rf $HOME/sway-arch/.vimrc "$HOME"
cp -rf $HOME/sway-arch/.config/ "$HOME"
cp -rf $HOME/sway-arch/.local/ "$HOME"
mkdir -p $HOME/.local/share/fonts/
cp -rf $HOME/tipografias/* "$HOME"/.local/share/fonts/
cp -rf $HOME/temas/.{icons,themes}/ "$HOME"
rm -rf "$HOME"/{sway-arch,tipografias,temas}/

# Software adicional
sudo pacman -S git kitty make gcc htop vim blueberry network-manager-applet pacman-contrib man bc polkit-gnome telegram-desktop imv mpv zathura-pdf-mupdf mousepad xdg-user-dirs python-pillow imagemagick --noconfirm --needed

# SwayWM
sudo pacman -S sway --noconfirm --needed
sudo pacman -S rtkit qt5-wayland xorg-xwayland swayidle wofi mako waybar grim slurp wl-clipboard wf-recorder brightnessctl --noconfirm --needed
sudo pacman -S xdg-desktop-portal xdg-desktop-portal-gtk xdg-desktop-portal-wlr --noconfirm --needed
sudo pacman -S wireplumber --noconfirm --needed

# Pipewire utilities
#sudo pacman -S alsa-utils pipewire-alsa pipewire-pulse bluez bluez-utils pavucontrol --noconfirm --needed

# Thunar extras
sudo pacman -S gvfs thunar thunar-archive-plugin thunar-volman thunar-archive-plugin tumbler ffmpegthumbnailer xarchiver zip unzip unrar unarj p7zip lzop lzip lrzip lha cpio arj --noconfirm --needed

# Fuentes basicas
sudo pacman -S ttf-{dejavu,hack,roboto,liberation} terminus-font wqy-microhei unicode-character-database noto-fonts noto-fonts-cjk --noconfirm --needed

# Display manager (pantalla de inicio de sesion)
sudo pacman -S lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings --noconfirm

# Paru AUR helper
clear 
printf '\n \nInstalando el gestor de paquetes Paru...\n'
sleep 1
cd ; git clone https://aur.archlinux.org/paru-bin.git ; cd paru-bin ; makepkg -si --noconfirm ; cd ; rm -rf paru-bin
sudo sed -i "s/#BottomUp/BottomUp/g" /etc/paru.conf 

## borrando directorios no necesarios
rm -rf "$HOME"/go/

sleep 1
printf '\n \nInstalando repositorio Chaotic para no depender de AUR'
clear
sudo pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com
sudo pacman-key --lsign-key FBA220DFC880C036
sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' --noconfirm
sudo tee -a /etc/pacman.conf <<EOF
[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist
EOF
sudo pacman -Sy --noconfirm
sudo pacman -S clipman --noconfirm

# Cambiando de fuente y wallpaper ligthDM
sudo tee /etc/lightdm/lightdm-gtk-greeter.conf <<EOF
[greeter]
font-name=SF Compact Display 9
xft-antialias=true
xft-dpi=96
xft-hintstyle=hintslight
xft-rgba=rgb
indicators=~session;~spacer;separator;~clock;~spacer;separator;~power;
clock-format=%a, %b %d, %H:%M
EOF

# Desinstalar terminal y menu obsoletos
clear
sudo pacman -Rs dmenu --noconfirm
sudo pacman -Rs alacritty --noconfirm
sudo pacman -Rs nano --noconfirm
sudo pacman -Rs foot --noconfirm

clear
sleep 1
printf '\n \nConfiguraciones aplicadas!'
sleep 1
printf '\n \nIniciando pantalla de inicio de session....'
clear
## Habilitando servicio de pantalla de inicio de sesion
sudo systemctl enable --now lightdm
## Habilitando servicio de bluetooth 
sudo systemctl enable --now bluetooth.service
#printf '\n \nConsulte los atajos del teclado en el archivo ~/.config/sway/config'
#sleep 1
#printf '\n \nReemplace el fondo de escritorio en .config/wall.*'
#sleep 1
#printf '\n \nContribuye paypal.me/hivz'
#sleep 1
#printf '\n \n'
