#!/bin/bash


rm -rf $HOME/.config/waybar/style.css
rm -rf $HOME/.config/wofi/style.css
cp $HOME/.config/wofi/temas/obscuro.css $HOME/.config/wofi/style.css
cp $HOME/.config/waybar/temas/obscuro.css $HOME/.config/waybar/style.css

sed -i "s/Orchis-light/Orchis-dark/g" $HOME/.config/sway/config
sed -i "s/Papirus-Light/Papirus-Dark/g" $HOME/.config/sway/config
sed -i "s/claro/obscuro/g" $HOME/.config/sway/config

sed -i "s/claro/obscuro/g" $HOME/.config/kitty/kitty.conf

swaymsg reload
