#!/bin/bash

rm -rf $HOME/.config/waybar/style.css
rm -rf $HOME/.config/wofi/style.css
cp $HOME/.config/wofi/temas/claro.css $HOME/.config/wofi/style.css
cp $HOME/.config/waybar/temas/claro.css $HOME/.config/waybar/style.css

sed -i "s/lightOrchis-dark/Orchis-light/g" $HOME/.config/sway/config
sed -i "s/Papirus-Dark/Papirus-Light/g" $HOME/.config/sway/config
sed -i "s/obscuro/claro/g" $HOME/.config/sway/config

sed -i "s/obscuro/claro/g" $HOME/.config/kitty/kitty.conf

swaymsg reload
