#!/bin/bash

notify-send --expire-time 10000 --icon $HOME/.config/user.png 'Cambiado a modo gris' 'La configuracion se aplicara en unos segundos...'

rm -rf $HOME/.config/waybar/style.css
rm -rf $HOME/.config/wofi/style.css
rm -rf $HOME/.config/wall.*

cp $HOME/.config/wallpaper/obscuro.* $HOME/.config/wall.jpg
cp $HOME/.config/wofi/temas/gris.css $HOME/.config/wofi/style.css
cp $HOME/.config/waybar/temas/gris.css $HOME/.config/waybar/style.css

sed -i "s/-light/-dark/g" $HOME/.config/sway/config
sed -i "s/-Light/-Dark/g" $HOME/.config/sway/config

sed -i "s/claro/gris/g" $HOME/.config/sway/config
sed -i "s/obscuro/gris/g" $HOME/.config/sway/config

sed -i "s/claro/gris/g" $HOME/.config/kitty/kitty.conf
sed -i "s/obscuro/gris/g" $HOME/.config/kitty/kitty.conf

sed -i "s/-light/-dark/g" $HOME/.gtkrc-2.0
sed -i "s/-Light/-Dark/g" $HOME/.gtkrc-2.0
sed -i "s/-light/-dark/g" $HOME/.config/gtk-3.0/settings.ini
sed -i "s/-Light/-Dark/g" $HOME/.config/gtk-3.0/settings.ini

sed -i "s/color=ffffff 505050/color=000000 dddddd/g" $HOME/.config/foot/foot.ini
sed -i "s/foreground=505050/foreground=dddddd/g" $HOME/.config/foot/foot.ini
sed -i "s/background=ffffff/background=242424/g" $HOME/.config/foot/foot.ini
sed -i "s/background=000000/background=242424/g" $HOME/.config/foot/foot.ini

swaymsg reload
