#!/bin/bash

notify-send --expire-time 10000 --icon $HOME/.config/user.png 'Cambiado a modo claro' 'La configuracion se aplicara en unos segundos...'

rm -rf $HOME/.config/waybar/style.css
rm -rf $HOME/.config/wofi/style.css
rm -rf $HOME/.config/wall.*

cp $HOME/.config/wallpaper/claro.* $HOME/.config/wall.jpg
cp $HOME/.config/wofi/temas/claro.css $HOME/.config/wofi/style.css
cp $HOME/.config/waybar/temas/claro.css $HOME/.config/waybar/style.css

sed -i "s/-dark/-light/g" $HOME/.config/sway/config
sed -i "s/-Dark/-light/g" $HOME/.config/sway/config

sed -i "s/obscuro/claro/g" $HOME/.config/sway/config
sed -i "s/gris/claro/g" $HOME/.config/sway/config

sed -i "s/obscuro/claro/g" $HOME/.config/kitty/kitty.conf
sed -i "s/gris/claro/g" $HOME/.config/kitty/kitty.conf

sed -i "s/-dark/-light/g" $HOME/.gtkrc-2.0
sed -i "s/-Dark/-light/g" $HOME/.gtkrc-2.0
sed -i "s/-dark/-light/g" $HOME/.config/gtk-3.0/settings.ini
sed -i "s/-Dark/-light/g" $HOME/.config/gtk-3.0/settings.ini

sed -i "s/color=000000 dddddd/color=ffffff 505050/g" $HOME/.config/foot/foot.ini
sed -i "s/foreground=dddddd/foreground=505050/g" $HOME/.config/foot/foot.ini
sed -i "s/background=000000/background=ffffff/g" $HOME/.config/foot/foot.ini
sed -i "s/background=242424/background=ffffff/g" $HOME/.config/foot/foot.ini

swaymsg reload
