#!/bin/bash

loco=$(printf "Bloquear\nCerrar sesion\nApagar\nReiniciar\nSuspender\nHibernar\nSuspencion hibrida\nSuspender y luego hibernar" | wofi \
      --dmenu \
      --width 200 \
      --lines 8 \
      --prompt Powermenu)

if [[ $loco = "Bloquear" ]]; then
	dm-tool lock
elif [[ $loco = "Cerrar sesion" ]]; then
	swaymsg exit
elif [[ $loco = "Apagar" ]]; then
	systemctl poweroff
elif [[ $loco = "Reiniciar" ]]; then
	systemctl reboot
elif [[ $loco = "Suspender" ]]; then
	systemctl suspend
elif [[ $loco = "Hibernar" ]]; then
	systemctl hibernate
elif [[ $loco = "Suspencion hibrida" ]]; then
	systemctl hybrid-sleep
elif [[ $loco = "Suspender y luego hibernar" ]]; then
	systemctl suspend-then-hibernate
fi
